// MCP server (stdio or HTTP) for Claude Desktop / Claude Code integration.
#![allow(dead_code)] // helpers are invoked through spawn_blocking/macro-generated code
// docs: https://docs.rs/rmcp/latest/rmcp/
// MCP spec: https://modelcontextprotocol.io/

use rmcp::{
    ServerHandler, ServiceExt,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    tool, tool_handler, tool_router,
    transport::stdio,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{
    config::{Config, collection_db_path},
    db,
    get::{MultiGetResult, fetch_document, fetch_document_with_config, open_readonly},
    index,
    types::SearchResult,
};

// ^ don't import crate::error::Result here — macro-generated code uses
//   std::result::Result<T,E> (2 params) and the name must not be shadowed.
type IrResult<T> = std::result::Result<T, crate::error::Error>;

// ── tool input types ──────────────────────────────────────────────────────────

/// A single filter predicate for the search tool.
/// Use multiple clauses (all ANDed) via the `filter` array on SearchInput.
#[derive(Debug, Deserialize, JsonSchema)]
struct FilterClauseInput {
    /// Field to filter on: path, modified_at, created_at, or meta.<name> (e.g. meta.tags)
    field: String,
    /// Comparison operator
    op: crate::types::FilterOp,
    /// Value to compare against. Dates for modified_at/created_at/meta.date accept YYYY-MM-DD or RFC3339.
    value: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct SearchInput {
    /// Search query text
    query: String,
    /// Search mode: bm25, vector, or hybrid (default: hybrid)
    mode: Option<String>,
    /// Maximum number of results to return (default: 10)
    limit: Option<usize>,
    /// Minimum relevance score 0.0–1.0 (default: none)
    min_score: Option<f64>,
    /// Restrict search to these collection names (default: all)
    collections: Option<Vec<String>>,
    /// Include full document content in results (default: false; returns snippet only)
    full: Option<bool>,
    /// Include best-matching chunk text in results (vector results only; ignored for BM25-only results)
    include_chunk: Option<bool>,
    /// Filter clauses (ANDed). Fields: path, modified_at, created_at, meta.<name>.
    /// Ops: =, !=, >, >=, <, <=, ~ (contains), !~ (not-contains).
    /// Example: [{"field":"modified_at","op":">=","value":"2024-01-01"},{"field":"meta.tags","op":"=","value":"rust"}]
    filter: Option<Vec<FilterClauseInput>>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct UpdateInput {
    /// Only update this collection name (default: all collections)
    collection: Option<String>,
    /// Force full re-index from scratch (default: false)
    force: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct GetInput {
    /// File path to retrieve. Exact match first, then suffix match, then substring.
    path: String,
    /// Restrict lookup to these collection names (default: all)
    collections: Option<Vec<String>>,
    /// Return only the named section (heading text match, case-insensitive; default: full document)
    section: Option<String>,
    /// Start output at this character offset into the document (default: 0)
    offset: Option<usize>,
    /// Truncate output to this many characters (default: no limit)
    max_chars: Option<usize>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct MultiGetInput {
    /// List of file paths to retrieve.
    paths: Vec<String>,
    /// Restrict lookup to these collection names (default: all)
    collections: Option<Vec<String>>,
    /// Truncate each document to this many characters (default: no limit)
    max_chars: Option<usize>,
}

// ── status / update output types ──────────────────────────────────────────────

#[derive(Serialize)]
struct CollectionStatus {
    name: String,
    path: String,
    indexed: bool,
    size_mb: f64,
    doc_count: Option<usize>,
}

#[derive(Serialize)]
struct StatusOutput {
    collections: Vec<CollectionStatus>,
    daemon_running: bool,
}

#[derive(Serialize)]
struct UpdateResult {
    collection: String,
    added: usize,
    updated: usize,
    deactivated: usize,
}

// ── server ────────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct IrMcpServer {
    // ^ tool_router field is injected by #[tool_router] at compile time
    tool_router: ToolRouter<Self>,
}

impl IrMcpServer {
    fn new() -> Self {
        // ^ Self::tool_router() is generated by #[tool_router] — pre-wired with all tools
        Self {
            tool_router: Self::tool_router(),
        }
    }
}

#[tool_router]
impl IrMcpServer {
    #[tool(
        description = "Hybrid BM25+vector search over indexed document collections. \
        Returns ranked results with file path, title, relevance score, and a text snippet. \
        Set full=true to include full document text inline. \
        Set include_chunk=true to include the best-matching chunk text inline (vector results only). \
        Use get or multi_get to retrieve full document text by path. \
        Use filter to narrow results by metadata: fields path, modified_at, created_at, meta.<name>; \
        ops =, !=, >, >=, <, <=, ~ (contains), !~ (not-contains); multiple clauses are ANDed."
    )]
    async fn search(&self, params: Parameters<SearchInput>) -> Result<String, String> {
        let SearchInput {
            query,
            mode,
            limit,
            min_score,
            collections,
            full,
            include_chunk,
            filter,
        } = params.0;
        let mode = mode.unwrap_or_else(|| "hybrid".to_string());
        let limit = limit.unwrap_or(10);
        let collections = collections.unwrap_or_default();
        let full = full.unwrap_or(false);
        let include_chunk = include_chunk.unwrap_or(false);
        let filter = crate::types::Filter::from_clauses(
            filter
                .unwrap_or_default()
                .into_iter()
                .map(|c| crate::types::FilterClause {
                    field: c.field,
                    op: c.op,
                    value: c.value,
                })
                .collect(),
        );
        spawn_tool(move || {
            let mut results = crate::search_core(
                &query,
                &mode,
                limit,
                min_score,
                &collections,
                crate::types::Verbosity::Quiet,
                filter,
            )?;
            if full && !results.is_empty() {
                fill_results_content(&mut results)?;
            } else if include_chunk {
                crate::get::populate_chunk_content(&mut results)?;
            }
            Ok(results)
        })
        .await
    }

    #[tool(
        description = "Show index health: collection names, paths, document counts, \
        DB sizes, and whether the search daemon is running."
    )]
    async fn status(&self) -> Result<String, String> {
        spawn_tool(build_status).await
    }

    #[tool(
        description = "Re-index document collections so newly added or changed files \
        become searchable. Runs synchronously — may take seconds to minutes for large collections."
    )]
    async fn update(&self, params: Parameters<UpdateInput>) -> Result<String, String> {
        let UpdateInput { collection, force } = params.0;
        let force = force.unwrap_or(false);
        spawn_tool(move || run_update(collection.as_deref(), force)).await
    }

    #[tool(
        description = "Retrieve the full text of a single document by file path. \
        Tries exact match first, then suffix match, then substring match across all collections. \
        Also accepts vault-root paths (e.g. 'Notes/2026/file.md' where 'Notes' is the collection dir). \
        Use section to retrieve a named heading section only (e.g. section='Installation'). \
        Returns a tool error if not found — use multi_get if you need a non-error response for misses."
    )]
    async fn get(&self, params: Parameters<GetInput>) -> Result<String, String> {
        let GetInput {
            path,
            collections,
            section,
            offset,
            max_chars,
        } = params.0;
        let collections = collections.unwrap_or_default();
        spawn_tool(move || {
            let mut doc = fetch_document(&path, &collections)?
                .ok_or_else(|| crate::error::Error::Other(format!("not found: {path}")))?;
            if let Some(ref heading) = section {
                doc.content = crate::get::extract_section(&doc.content, heading)
                    .unwrap_or("")
                    .to_string();
            }
            if offset.is_some() || max_chars.is_some() {
                doc.content = crate::get::trim_content(&doc.content, offset, max_chars).to_string();
            }
            Ok(doc)
        })
        .await
    }

    #[tool(
        description = "Retrieve the full text of multiple documents by file path in one call. \
        Each path is resolved independently (exact → suffix → substring match). \
        Returns found documents and a list of unmatched paths."
    )]
    async fn multi_get(&self, params: Parameters<MultiGetInput>) -> Result<String, String> {
        let MultiGetInput {
            paths,
            collections,
            max_chars,
        } = params.0;
        let collections = collections.unwrap_or_default();
        spawn_tool(move || {
            let config = Config::load()?;
            let mut found = Vec::new();
            let mut not_found = Vec::new();
            for path in &paths {
                match fetch_document_with_config(path, &collections, &config)? {
                    Some(mut doc) => {
                        if max_chars.is_some() {
                            doc.content =
                                crate::get::trim_content(&doc.content, None, max_chars).to_string();
                        }
                        found.push(doc);
                    }
                    None => not_found.push(path.clone()),
                }
            }
            Ok(MultiGetResult { found, not_found })
        })
        .await
    }
}

#[tool_handler]
impl ServerHandler for IrMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("ir", env!("CARGO_PKG_VERSION")))
            .with_instructions(build_instructions())
    }
}

// ── tool response helpers ─────────────────────────────────────────────────────

/// Run a blocking function on a thread pool and return its result as JSON.
async fn spawn_tool<F, T>(f: F) -> Result<String, String>
where
    F: FnOnce() -> IrResult<T> + Send + 'static,
    T: Serialize + Send + 'static,
{
    match tokio::task::spawn_blocking(f).await {
        Ok(Ok(v)) => ok_json(&v),
        Ok(Err(e)) => Err(e.to_string()),
        Err(e) => Err(format!("internal: {e}")),
    }
}

fn ok_json(v: &impl Serialize) -> Result<String, String> {
    serde_json::to_string_pretty(v).map_err(|e| format!("serialization failed: {e}"))
}

// ── server instructions ───────────────────────────────────────────────────────

fn build_instructions() -> String {
    let config = Config::load().ok().filter(|c| !c.collections.is_empty());
    let Some(config) = config else {
        return "ir local search engine. No collections configured. \
                Run `ir collection add <name> <path>` to add one."
            .to_string();
    };

    let cols: Vec<String> = config
        .collections
        .iter()
        .map(|c| {
            let db_path = collection_db_path(&c.name);
            let suffix = if db_path.exists() {
                count_docs(&db_path)
                    .map(|n| format!(", {n} docs"))
                    .unwrap_or_default()
            } else {
                " (not indexed)".to_string()
            };
            format!("{} ({}{})", c.name, c.path, suffix)
        })
        .collect();

    format!(
        "ir local search engine. Collections: {}. \
        Use `search` for hybrid BM25+vector retrieval, `get` or `multi_get` to retrieve \
        full document text by path, `status` for index health, \
        `update` to re-index after file changes.",
        cols.join("; ")
    )
}

// ── helpers ───────────────────────────────────────────────────────────────────

fn fill_results_content(results: &mut [SearchResult]) -> IrResult<()> {
    let config = Config::load()?;
    let col_names: std::collections::HashSet<&str> =
        results.iter().map(|r| r.collection.as_str()).collect();
    let dbs: Vec<db::CollectionDb> = col_names
        .iter()
        .filter_map(|name| config.get_collection(name))
        .map(|c| {
            let pp_aliases = c.preprocessor.as_deref().unwrap_or(&[]);
            let pp_commands = config.resolve_preprocessor_commands(pp_aliases);
            db::CollectionDb::open_rw(
                &c.name,
                &collection_db_path(&c.name),
                pp_commands,
                c.routing.clone(),
                c.retrieval.clone(),
            )
        })
        .collect::<crate::error::Result<Vec<_>>>()?;
    crate::fill_content(results, &dbs);
    Ok(())
}

fn count_docs(db_path: &std::path::Path) -> Option<usize> {
    db::ensure_sqlite_vec();
    let conn = open_readonly(db_path).ok()?;
    conn.query_row(
        "SELECT COUNT(*) FROM documents WHERE active = 1",
        [],
        |row| row.get::<_, usize>(0),
    )
    .ok()
}

fn build_status() -> IrResult<StatusOutput> {
    let config = Config::load()?;
    let mut collections = Vec::new();
    for col in &config.collections {
        let db_path = collection_db_path(&col.name);
        let size_bytes = std::fs::metadata(&db_path).ok().map(|m| m.len());
        let indexed = size_bytes.is_some();
        let size_mb = size_bytes.unwrap_or(0) as f64 / 1_048_576.0;
        let doc_count = if indexed { count_docs(&db_path) } else { None };
        collections.push(CollectionStatus {
            name: col.name.clone(),
            path: col.path.clone(),
            indexed,
            size_mb,
            doc_count,
        });
    }
    Ok(StatusOutput {
        collections,
        daemon_running: crate::daemon::is_running(),
    })
}

fn run_update(collection: Option<&str>, force: bool) -> IrResult<Vec<UpdateResult>> {
    let config = Config::load()?;
    let cols: Vec<_> = match collection {
        Some(name) => {
            let c = config
                .get_collection(name)
                .ok_or_else(|| crate::error::Error::CollectionNotFound(name.to_string()))?;
            vec![c]
        }
        None => config.collections.iter().collect(),
    };

    let mut results = Vec::new();
    for col in cols {
        let db_path = collection_db_path(&col.name);
        let pp_aliases = col.preprocessor.as_deref().unwrap_or(&[]);
        let has_preprocessor = !config.resolve_preprocessor_commands(pp_aliases).is_empty();
        let db_conn = db::CollectionDb::open(&col.name, &db_path, has_preprocessor)?;
        let opts = index::UpdateOptions { force };
        let (added, updated, deactivated) = index::update(&db_conn, col, &opts, &config)?;
        results.push(UpdateResult {
            collection: col.name.clone(),
            added,
            updated,
            deactivated,
        });
    }
    Ok(results)
}

// ── entry point ───────────────────────────────────────────────────────────────

pub async fn run(http: Option<u16>, cors: Option<String>) -> IrResult<()> {
    match http {
        None => run_stdio().await,
        Some(port) => run_http(port, cors).await,
    }
}

async fn run_stdio() -> IrResult<()> {
    let service = IrMcpServer::new()
        .serve(stdio())
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))?;
    service
        .waiting()
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))?;
    Ok(())
}

fn build_cors_layer(origin: &str) -> IrResult<tower_http::cors::CorsLayer> {
    use axum::http::{HeaderValue, Method, header};
    use tower_http::cors::CorsLayer;

    let allow_origin = if origin == "*" {
        tower_http::cors::AllowOrigin::any()
    } else {
        let val = origin
            .parse::<HeaderValue>()
            .map_err(|_| crate::error::Error::Other(format!("invalid --cors value: {origin:?}")))?;
        tower_http::cors::AllowOrigin::exact(val)
    };
    Ok(CorsLayer::new()
        .allow_origin(allow_origin)
        .allow_methods([Method::GET, Method::POST, Method::DELETE])
        .allow_headers([
            header::CONTENT_TYPE,
            header::ACCEPT,
            header::HeaderName::from_static("mcp-session-id"),
            header::HeaderName::from_static("mcp-protocol-version"),
            header::HeaderName::from_static("last-event-id"),
        ])
        .expose_headers([header::HeaderName::from_static("mcp-session-id")]))
}

async fn run_http(port: u16, cors: Option<String>) -> IrResult<()> {
    use rmcp::transport::streamable_http_server::{
        StreamableHttpServerConfig, StreamableHttpService, session::local::LocalSessionManager,
    };

    let wildcard_cors = cors.as_deref() == Some("*");
    // Wildcard CORS makes the endpoint fully public; rmcp's host check adds no protection.
    let mut config = StreamableHttpServerConfig::default();
    if wildcard_cors {
        config = config.disable_allowed_hosts();
    }

    let cors_layer = cors.as_deref().map(build_cors_layer).transpose()?;

    let service = StreamableHttpService::new(
        || Ok(IrMcpServer::new()),
        LocalSessionManager::default().into(),
        config,
    );

    let addr = format!("0.0.0.0:{port}");
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .map_err(|e| crate::error::Error::Other(format!("bind {addr}: {e}")))?;
    eprintln!("ir MCP server listening on http://{addr}/mcp");

    let router = axum::Router::new().nest_service("/mcp", service);
    let router = match cors_layer {
        Some(layer) => router.layer(layer),
        None => router,
    };
    axum::serve(listener, router)
        .with_graceful_shutdown(async {
            tokio::signal::ctrl_c().await.ok();
        })
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cors_layer_wildcard() {
        assert!(build_cors_layer("*").is_ok());
    }

    #[test]
    fn cors_layer_exact_origin() {
        assert!(build_cors_layer("https://example.com").is_ok());
    }

    #[test]
    fn cors_layer_rejects_invalid_origin() {
        // Control characters are not valid header values.
        assert!(build_cors_layer("bad\x00value").is_err());
    }

    #[test]
    fn cors_layer_rejects_newline_injection() {
        assert!(build_cors_layer("https://ok.com\r\nX-Injected: evil").is_err());
    }
}
